### PR TITLE
add signing to sign the binaries generated using cosign

### PR DESCRIPTION
**Pull request by cpanato**
Add a step in goreleaser to sign the binaries generated using sigstore cosign.

cc @another-rex

### CODE REVIEW

**Comment by laurentsimon** [comment]
The project already generates SLSA attestations, see https://github.com/google/osv-scanner/blob/main/.github/workflows/goreleaser.yml#L44-L53 and https://github.com/google/osv-scanner/releases/tag/v1.0.0

I don't think cosign signatures are needed, since attestation provide the same guarantees plus additional info (GH context, etc)

**Comment by asraa** [comment]
> I don't think cosign signatures are needed, since attestation provide the same guarantees plus additional info (GH context, etc)

+1 although I think we could add a snippet into the README.md about how to verify the SLSA provenance in the release assets and what information is there with a quick jq command. WDYT? I can do as a follow-up if people agree

**Comment by oliverchang** [comment]
> > I don't think cosign signatures are needed, since attestation provide the same guarantees plus additional info (GH context, etc)
> 
> +1 although I think we could add a snippet into the README.md about how to verify the SLSA provenance in the release assets and what information is there with a quick jq command. WDYT? I can do as a follow-up if people agree

Yes please!

**Comment by cpanato** [comment]
closing

**Pull request closed without merging**
