### PR TITLE
Snap created

### PR DESCRIPTION
**Pull request by kz6fittycent**
I've created a working [snap](https://snapcraft.io/about) (built and tested locally). This could be published to the [snap store](https://snapcraft.io/store) and would for installation across all supported Linux distros. 

This would require registration and [collaboration w/ Canonical](https://forum.snapcraft.io/t/process-for-reviewing-classic-confinement-snaps/1460) to gain approval for `classic` confinement. I'm able to help with it, if you'd like.

### CODE REVIEW

**Comment by oliverchang** [comment]
Thanks for your contribution! We would love for this to be published to the snap store, and would appreciate your help.

**Comment by kz6fittycent** [comment]
a representative from the team will need to create an account on forum.snapcraft.io and we can create a new thread to request `classic` confinement. It'll go thru a review process since it allows the snap to run like 'native' on an OS. I can start the thread, but they're going to want one of you to give the nod to the snap being "official".

**Comment by kz6fittycent** [comment]
It'll also need to get published - I can do that for you with my account but most times the upstream team wants to maintain the snap themselves. Meaning the team would need an account to control builds and publication.

**Review by Spiritaine — APPROVED** [review]

**Comment by another-rex** [comment]
A snap is created/maintained now by Canonical now: https://snapcraft.io/osv-scanner

**Pull request closed without merging**
