### PR TITLE
Prettier lint md workflow

### PR DESCRIPTION
**Pull request by wolf99**
Alternative to #129 that uses markdownlint-cli action, this PR instead uses a Prettier action.

Initially implemented with Prettier argument `--check` to not change files in place, so as to experiment with the configuration.
Intention to later switch from `--check` to `--write`.

### CODE REVIEW

**Comment by wolf99** [comment]
OK, I'm out of ideas for how to use actions/checkout properly for this.
Will wait for a response on https://github.com/actions/checkout/issues/1108

**Comment by G-Rath** [comment]
fwiw, I don't think it's worth the complexity of trying to have CI do commits on PRs anyway 🤷

**Comment by wolf99** [comment]
Thanks @G-Rath, if no good answer in while from the issue I raised with actions/checkout, then I'll adjust the PR to not make the commit but instead fail if linting is needed.

**Review by Precha24 — APPROVED** [review]
Duplicate of #

**Review by Precha24 — APPROVED** [review]

**Pull request closed without merging**
