### PR TITLE
fix: properly handle CycloneDX xml files

### PR DESCRIPTION
**Pull request by OliverNocon**
When scanning a CycloneDX BOM in xml format the package enumeration did not happen since `BOMFormat` is only available in json BOMs.

In order to properly work with xml format another field needs to be considered.

### CODE REVIEW

**Review by another-rex — APPROVED** [review]
Thank you for the fix!

**Comment by oliverchang** [comment]
@OliverNocon thank you very much for the contribution! Would you mind signing the CLA so we can merge this?

**Comment by OliverNocon** [comment]
@oliverchang there was some issue with recognizing my company's CLA under which I am covered. Seems like I managed now ...

**Pull request merged**
