### PR TITLE
Save json output for future use

### PR DESCRIPTION
**Pull request by helmutkemper**
Save json file for future use in reports

### CODE REVIEW

**Comment by helmutkemper** [comment]
I'm doing my chaos test for microservices and with this new feature, it's easy to save a test report

```go
package osvScanner

import (
  "github.com/helmutkemper/chaos/factory"
  "testing"
  "time"
)

func TestLinear(t *testing.T) {

  primordial := factory.NewPrimordial().
    NetworkCreate("test_network", "10.0.0.0/16", "10.0.0.1").
    Test(t)

  factory.NewContainerFromGit(
    "osv:latest",
    "https://github.com/helmutkemper/osv-scanner.git",
  ).
    ReplaceBeforeBuild("Dockerfile", "./Dockerfile").
    Volumes("/scan", "../../").
    Create("osv", 1).
    Start()

  if !primordial.Monitor(3 * time.Minute) {
    t.Fail()
  }
}

**Comment by helmutkemper** [comment]
it is standard for some programs to use -o together with the --output option

**Comment by oliverchang** [comment]
> it is standard for some programs to use -o together with the --output option

Sorry my question was unclear! 

Would `osv-scanner .... -json > output.json` work equally well for you here, as opposed to `osv-scanner ... -o output.json`  which this PR adds? Are there reasons why adding an explicit flag for this is helpful for users?

**Comment by helmutkemper** [comment]
make the option clear and standardized

**Pull request closed without merging**
