### PR TITLE
feat: improved error message when pom dependency version not found

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Comment by G-Rath** [comment]
I'm not sure how useful this change is? shouldn't you be able to figure out the pom based on the dependency name and the property name that is being accessed?

I'm not a heavy Java user, so would appreciate if you could expand on the situation you're dealing with where the current warning is not sufficient.

(also @oliverchang or @another-rex could you approve the CI workflows to run?)

**Comment by raboof** [comment]
> I'm not sure how useful this change is? shouldn't you be able to figure out the pom based on the dependency name and the property name that is being accessed?
> 
> I'm not a heavy Java user, so would appreciate if you could expand on the situation you're dealing with where the current warning is not sufficient.

I guess it depends on how the library is being used. I came to this from [scorecard](https://github.com/ossf/scorecard), and there for example you would currently see:

```
$ scorecard --repo=github.com/apache/camel-examples
Starting [SAST]
Starting [License]
Starting [Code-Review]
Starting [CII-Best-Practices]
Starting [Maintained]
Starting [Fuzzing]
Starting [Dangerous-Workflow]
Starting [Pinned-Dependencies]
Starting [Security-Policy]
Starting [CI-Tests]
Starting [Dependency-Update-Tool]
Starting [Contributors]
Starting [Binary-Artifacts]
Starting [Vulnerabilities]
Starting [Packaging]
Starting [Signed-Releases]
Starting [Branch-Protection]
Starting [Token-Permissions]
Failed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.derby:derby: property "derby-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.junit.jupiter:junit-jupiter: property "junit-jupiter-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of ch.qos.logback:logback-core: property "logback-version" could not be foundFailed to resolve version of ch.qos.logback:logback-classic: property "logback-version" could not be foundFailed to resolve version of ch.qos.logback:logback-core: property "logback-version" could not be foundFailed to resolve version of ch.qos.logback:logback-classic: property "logback-version" could not be foundFailed to resolve version of ch.qos.logback:logback-core: property "logback-version" could not be foundFailed to resolve version of ch.qos.logback:logback-classic: property "logback-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.camel:camel-test-infra-kafka: property "project.version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.camel:camel-test-infra-kafka: property "project.version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.camel:camel-test-infra-kafka: property "project.version" could not be foundFailed to resolve version of org.apache.camel:camel-test-main-junit5: property "camel.version" could not be foundFailed to resolve version of org.apache.camel:camel-test-infra-aws-v2: property "project.version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of com.fasterxml.woodstox:woodstox-core: property "woodstox-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.commons:commons-lang3: property "commons-lang3-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.camel:camel-test-infra-couchbase: property "project.version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.camel:camel-test-infra-aws-v2: property "project.version" could not be foundFailed to resolve version of org.apache.camel:camel-test-infra-postgres: property "project.version" could not be foundFailed to resolve version of org.apache.camel:camel-test-infra-cassandra: property "project.version" could not be foundFailed to resolve version of org.awaitility:awaitility: property "awaitility-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.junit.jupiter:junit-jupiter: property "junit-jupiter-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.ftpserver:ftpserver-core: property "ftpserver-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.commons:commons-lang3: property "commons-lang3-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-jul: property "log4j2-version" could not be foundFailed to resolve version of org.springframework:spring-jdbc: property "spring-version" could not be foundFailed to resolve version of org.apache.derby:derby: property "derby-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of junit:junit: property "junit-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.hsqldb:hsqldb: property "hsqldb-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.camel:camel-test-infra-kafka: property "project.version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of io.rest-assured:kotlin-extensions: property "rest-assured-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.camel:camel-test-infra-minio: property "project.version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.camel:camel-test-infra-mongodb: property "project.version" could not be foundFailed to resolve version of io.rest-assured:rest-assured: property "rest-assured-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.camel:camel-log: property "project.version" could not be foundFailed to resolve version of org.apache.camel:camel-caffeine: property "project.version" could not be foundFailed to resolve version of org.apache.camel:camel-aws2-kinesis: property "project.version" could not be foundFailed to resolve version of org.apache.camel.example:resume-api-common: property "project.version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.camel:camel-test-infra-aws-v2: property "project.version" could not be foundFailed to resolve version of org.apache.camel:camel-caffeine: property "project.version" could not be foundFailed to resolve version of org.apache.camel:camel-cassandraql: property "project.version" could not be foundFailed to resolve version of org.apache.camel.example:resume-api-common: property "project.version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.camel.example:resume-api-common: property "project.version" could not be foundFailed to resolve version of org.apache.camel.example:resume-api-common: property "project.version" could not be foundFailed to resolve version of org.apache.camel.example:resume-api-common: property "project.version" could not be foundFailed to resolve version of org.apache.camel.example:resume-api-common: property "project.version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.activemq:activemq-broker: property "activemq-version" could not be foundFailed to resolve version of org.apache.activemq:activemq-client: property "activemq-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.junit.jupiter:junit-jupiter-api: property "junit-jupiter-version" could not be foundFailed to resolve version of org.junit.jupiter:junit-jupiter-engine: property "junit-jupiter-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.camel:camel-test-infra-pulsar: property "project.version" could not be foundFailed to resolve version of org.springframework.security:spring-security-web: property "spring-security-version" could not be foundFailed to resolve version of org.springframework:spring-web: property "spring-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.jboss.arquillian.container:arquillian-tomcat-embedded-9: property "arquillian-tomcat-version" could not be foundFailed to resolve version of org.apache.tomcat.embed:tomcat-embed-jasper: property "tomcat-version" could not be foundFailed to resolve version of org.junit.jupiter:junit-jupiter: property "junit-jupiter-version" could not be foundFailed to resolve version of org.jboss.arquillian.junit5:arquillian-junit5-container: property "arquillian-version" could not be foundFailed to resolve version of io.rest-assured:rest-assured: property "rest-assured-version" could not be foundFailed to resolve version of org.apache.activemq:activemq-broker: property "activemq-version" could not be foundFailed to resolve version of org.apache.activemq:activemq-client: property "activemq-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.springframework:spring-context: property "spring-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-core: property "log4j2-version" could not be foundFailed to resolve version of org.apache.logging.log4j:log4j-slf4j2-impl: property "log4j2-version" could not be foundFinished [Vulnerabilities]
Finished [Packaging]
Finished [Signed-Releases]
Finished [Branch-Protection]
Finished [Token-Permissions]
Finished [SAST]
Finished [License]
Finished [Code-Review]
Finished [CII-Best-Practices]
Finished [Maintained]
Finished [Fuzzing]
Finished [Dangerous-Workflow]
Finished [Binary-Artifacts]
Finished [Pinned-Dependencies]
Finished [Security-Policy]
Finished [CI-Tests]
Finished [Dependency-Update-Tool]
Finished [Contributors]
``` 

It's not super obvious those messages have anything to do with `pom.xml`'s in that repo in the first place, let alone which ones. While there's of course only so much you can do from the osv-scanner side, and ultimately perhaps something should change on the scorecard side, I'd say the change in this PR would be a nice improvement already.

**Comment by G-Rath** [comment]
(on an aside, I am annoying I forgot to add the `\n` at the end of that output 🙄🤦)

Yeah I agree that output is not the best, though I think the problem is more with these outputs being done inefficiently because at the time I didn't want to commit to a specific way to surface them given it would impact the library function signatures and be just a whole "thing"...

(I've explored a solution to this in #186 - any thoughts you'd have would be appreciated!)

My concern with this change is that we're now expecting and promising more info out of the file, and that typically means more cases to handle (i.e. what happens if it's not there) - however I assume these two properties are always present in a `pom.xml` anyway (+ the way we're using them shouldn't actually cause a panic) and I agree that this is an improvement at least until something like #186 is landed (which'll allow scorecard to actually handle these warnings)

**Comment by raboof** [comment]
> (on an aside, I am annoying I forgot to add the `\n` at the end of that output roll_eyesfacepalm)

:)

> Yeah I agree that output is not the best, though I think the problem is more with these outputs being done inefficiently because at the time I didn't want to commit to a specific way to surface them given it would impact the library function signatures and be just a whole "thing"...
> 
> (I've explored a solution to this in #186 - any thoughts you'd have would be appreciated!)

Yeah, something more 'controlled' like that would be great long-term, but coming up with what exactly that should look like is indeed not so easy :) .

> My concern with this change is that we're now expecting and promising more info out of the file, and that typically means more cases to handle (i.e. what happens if it's not there) - however I assume these two properties are always present in a `pom.xml` anyway (+ the way we're using them shouldn't actually cause a panic)

I actually tested this with some poms that didn't have a GroupID and that indeed looked pretty OK.

> I agree that this is an improvement at least until something like #186 is landed (which'll allow scorecard to actually handle these warnings)

Jup - it should probably still print it, but for example prefixing it with the "check" it belongs to and perhaps the file it's processing would be really useful to be able to do, and looks like it might be fairly easy to plug into that structure (Famous Last Words).

**Review by another-rex — APPROVED** [review]
Thanks, looks good to me as a middle ground before #186 is landed.

**Comment by raboof** [comment]
> [another-rex](https://github.com/another-rex) removed this pull request from the merge queue due to the queue being cleared

Does this mean there is action required on my part?

**Comment by another-rex** [comment]
> > [another-rex](https://github.com/another-rex) removed this pull request from the merge queue due to the queue being cleared
> 
> Does this mean there is action required on my part?

Ah no, was just trying out the merge queue, turns out still doesn't quite work for our repo. Going to merge this in soon.

**Pull request merged**
