### PR TITLE
refactor: just disable color output rather than tracking terminal width

### PR DESCRIPTION
**Pull request by G-Rath**
This lets us drop some conditionals - weirdly it doesn't seem to work if we move the conditional `text.DisableColors` call into `reporter.New` even though that does work for the vertical reporter...

### CODE REVIEW

**Review by another-rex — APPROVED** [review]
Thanks!

**Comment by another-rex** [comment]
> This lets us drop some conditionals - weirdly it doesn't seem to work if we move the conditional `text.DisableColors` call into `reporter.New` even though that does work for the vertical reporter...

Maybe it's because there multiple reporter.New() calls every run, and the disable color function is a single global variable.

**Comment by G-Rath** [comment]
yeahhhhh but then why would it work for the vertical output...? something odd is def going on but I think it's probably best we deal with that once we've landed the vertical report since we plan to shuffle things around a bit re table anyway right

**Comment by G-Rath** [comment]
Weirdly too it seems like it's a very stable global? I've run the test suite a ton and it never seems to give different results like I'd expect if this is an unstable use of a global...?

(fwiw I vote we land this for now - we can easily revert if it turns out to be flakey)

**Review by hogo6002 — APPROVED** [review]

**Pull request merged**
