### PR TITLE
Remove "working doc" concept

### PR DESCRIPTION
**Pull request by hayleycd**
Please preview changes here: https://hayleycd.github.io/osv-scanner/

Based on discussion with @oliverchang I have removed the working doc concept. We will be building docs from a stable branch. 

There wasn't a ton of difference between the working docs and current docs at this point, and I tried to combine them and use the preview label. Mostly govulncheck related.

Addresses #273

### CODE REVIEW

**Comment by oliverchang** [comment]
Thanks! Before this goes out, we also need to update the stable branch as well right?

**Comment by oliverchang** [comment]
> @oliverchang
> 
> I'm not sure what you are getting at. I believe we are currently building the docs from the main branch, and we will want to specify another one to build from.

Right, so before this one gets merged, we need to update the stable branch and point docs to it right? Otherwise the docs will be built from this one which is no accurate for the last stable release.

**Comment by hayleycd** [comment]
> > @oliverchang
> > I'm not sure what you are getting at. I believe we are currently building the docs from the main branch, and we will want to specify another one to build from.
> 
> Right, so before this one gets merged, we need to update the stable branch and point docs to it right? Otherwise the docs will be built from this one which is no accurate for the last stable release.

Yes! I think we are on the same page. Add the current state of docs to the stable branch and make sure the github page is building from it instead of main.

**Review by another-rex — APPROVED** [review]
LGTM!

**Pull request merged**
